# Generated by Django 2.0.5 on 2018-05-06 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CensusLearnSql',
            fields=[
                ('age', models.IntegerField(blank=True, null=True)),
                ('class_of_worker', models.CharField(blank=True, db_column='class of worker', max_length=1000, null=True)),
                ('industry_code', models.CharField(blank=True, db_column='industry code', max_length=1000, null=True)),
                ('occupation_code', models.CharField(blank=True, db_column='occupation code', max_length=1000, null=True)),
                ('education', models.CharField(blank=True, max_length=1000, null=True)),
                ('wage_per_hour', models.CharField(blank=True, db_column='wage per hour', max_length=1000, null=True)),
                ('last_education', models.CharField(blank=True, db_column='last education', max_length=1000, null=True)),
                ('marital_status', models.CharField(blank=True, db_column='marital status', max_length=1000, null=True)),
                ('major_industry_code', models.CharField(blank=True, db_column='major industry code', max_length=1000, null=True)),
                ('major_occupation_code', models.CharField(blank=True, db_column='major occupation code', max_length=1000, null=True)),
                ('mace', models.CharField(blank=True, max_length=1000, null=True)),
                ('hispanice', models.CharField(blank=True, max_length=1000, null=True)),
                ('sex', models.CharField(blank=True, max_length=1000, null=True)),
                ('member_of_labor', models.CharField(blank=True, db_column='member of labor', max_length=1000, null=True)),
                ('reason_for_unemployment', models.CharField(blank=True, db_column='reason for unemployment', max_length=1000, null=True)),
                ('fulltime', models.CharField(blank=True, max_length=1000, null=True)),
                ('capital_gain', models.CharField(blank=True, db_column='capital gain', max_length=1000, null=True)),
                ('capital_loss', models.CharField(blank=True, db_column='capital loss', max_length=1000, null=True)),
                ('dividends', models.CharField(blank=True, max_length=1000, null=True)),
                ('income_tax_liability', models.CharField(blank=True, db_column='income tax liability', max_length=1000, null=True)),
                ('previous_residence_region', models.CharField(blank=True, db_column='previous residence region', max_length=1000, null=True)),
                ('previous_residence_state', models.CharField(blank=True, db_column='previous residence state', max_length=1000, null=True)),
                ('household_with_family', models.CharField(blank=True, db_column='household-with-family', max_length=1000, null=True)),
                ('household_simple', models.CharField(blank=True, db_column='household-simple', max_length=1000, null=True)),
                ('weight', models.CharField(blank=True, max_length=1000, null=True)),
                ('msa_change', models.CharField(blank=True, db_column='msa-change', max_length=1000, null=True)),
                ('reg_change', models.CharField(blank=True, db_column='reg-change', max_length=1000, null=True)),
                ('within_reg_change', models.CharField(blank=True, db_column='within-reg-change', max_length=1000, null=True)),
                ('lived_here', models.CharField(blank=True, db_column='lived-here', max_length=1000, null=True)),
                ('migration_prev_res_in_sunbelt', models.CharField(blank=True, db_column='migration prev res in sunbelt', max_length=1000, null=True)),
                ('num_persons_worked_for_employer', models.CharField(blank=True, db_column='num persons worked for employer', max_length=1000, null=True)),
                ('family_members_under_118', models.CharField(blank=True, db_column='family members under 118', max_length=1000, null=True)),
                ('father_birth_country', models.CharField(blank=True, db_column='father birth country', max_length=1000, null=True)),
                ('mother_birth_country', models.CharField(blank=True, db_column='mother birth country', max_length=1000, null=True)),
                ('birth_country', models.CharField(blank=True, db_column='birth country', max_length=1000, null=True)),
                ('citizenship', models.CharField(blank=True, max_length=1000, null=True)),
                ('own_business_or_self_employed', models.CharField(blank=True, db_column='own business or self employed', max_length=1000, null=True)),
                ('fill_questionnaire_for_veteran_s_admin', models.CharField(blank=True, db_column="fill questionnaire for veteran's admin", max_length=1000, null=True)),
                ('veterans_benefits', models.CharField(blank=True, db_column='veterans benefits', max_length=1000, null=True)),
                ('weeks_worked_in_year', models.CharField(blank=True, db_column='weeks worked in year', max_length=1000, null=True)),
                ('year', models.CharField(blank=True, max_length=1000, null=True)),
                ('salary_range', models.CharField(blank=True, db_column='salary range', max_length=1000, null=True)),
            ],
            options={
                'db_table': 'census_learn_sql',
                'managed': False,
            },
        ),
    ]
